name: "ask-ai"
description: "Enhance PR reviews by querying AI with your questions."

inputs:
  openai-api-key:
    description: "OpenAI API key"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  model:
    description: "Model to use"
    required: false
    default: "gpt-3.5-turbo-0613"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require(`${process.env.GITHUB_ACTION_PATH}/main.js`);
          const openai_api_key = "${{ inputs.openai-api-key }}";
          const model = "${{ inputs.model }}";
          await script({ github, context, fetch, openai_api_key, model });
